IS_Turizmas/Controllers/RoutesController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using IS_Turizmas.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace IS_Turizmas.Controllers
{
    public class RoutesController : HomeController
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<RegistruotiVartotojai> _signInManager;

        public RoutesController(ApplicationDbContext context, SignInManager<RegistruotiVartotojai> signInManager):base(context)
        {
            _context = context;
            _signInManager = signInManager;
        }
        public async Task<IActionResult> Index()
        {
            Console.WriteLine("Called");
            var userId = _signInManager.UserManager.GetUserId(User);
            if (userId == null)
            {
                return LocalRedirect("/");
            }
            int id = int.Parse(userId);
            return View(await _context.Marsrutai.Include(o => o.MarsrutoObjektai).Where(o => o.FkRegistruotasVartotojas==id).ToListAsync());
        }

        public async Task<IActionResult> CreateRouteDescription()
        {
            if (_signInManager.IsSignedIn(User))
            {
                ViewBag.LaikoIverciai = _context.LaikoIverciai.ToList();
                return View();
            }
            else
            {
                return LocalRedirect("/");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateDescription([Bind("Pavadinimas, Aprasymas, LaikoIvertis, IslaidosNuo, IslaidosIki")]
        Marsrutai route)
        {
            route.SukurimoData = DateTime.Now;
            route.ModifikavimoData = DateTime.Now;
            //System.Security.Claims.ClaimsPrincipal currentUser = this.User;
            //route.FkRegistruotasVartotojas = int.Parse(_signInManager.UserManager.GetUserId(User));
            route.FkRegistruotasVartotojas = int.Parse(_signInManager.UserManager.GetUserId(User));
            if (!ModelState.IsValid)
            {
                ViewBag.LaikoIverciai = _context.LaikoIverciai.ToList();
                return View("~/Views/Routes/CreateRouteDescription.cshtml");
            }
            try
            {
                _context.Marsrutai.Add(route);
                var userController = new UserController(_context, _signInManager, null, null);
                userController.AddActivityPoints(10, _context.RegistruotiVartotojai.Find(int.Parse(_signInManager.UserManager.GetUserId(User))));
                TempData["AddedPoints"] = "Gavote 10 aktyvumo balų";
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return NotFound();
                throw;
            }
            TempData["SuccessMessage"] = "Maršruto aprašymas sukurtas";
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> EditRouteDescription(int id)
        {
            if (_signInManager.IsSignedIn(User)&& 
                _context.Marsrutai.FirstOrDefault(o => o.Id == id).FkRegistruotasVartotojas == int.Parse(_signInManager.UserManager.GetUserId(User)))
            {
                ViewBag.LaikoIverciai = _context.LaikoIverciai.ToList();
                return View(await _context.Marsrutai.FirstOrDefaultAsync(o => o.Id == id));
            }
            else
            {
                return LocalRedirect("/");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditDescription(int id, [Bind("Id,Pavadinimas, Aprasymas, LaikoIvertis," +
            " IslaidosNuo, IslaidosIki")] Marsrutai route)
        {
            if(id!= route.Id)
            {
                return NotFound();
            }
            Marsrutai oldRoute = _context.Marsrutai.Find(id);
            if (oldRoute.FkRegistruotasVartotojas != int.Parse(_signInManager.UserManager.GetUserId(User))){
                return NotFound();
            }
            oldRoute.Pavadinimas = route.Pavadinimas;
            oldRoute.Aprasymas = route.Aprasymas;
            oldRoute.LaikoIvertis = route.LaikoIvertis;
            oldRoute.IslaidosNuo = route.IslaidosNuo;
            oldRoute.IslaidosIki = route.IslaidosIki;
            oldRoute.ModifikavimoData = DateTime.Now;
            if (!ModelState.IsValid)
            {
                ViewBag.LaikoIverciai = _context.LaikoIverciai.ToList();
                return View("~/Views/Routes/EditRouteDescription.cshtml");
            }
            try
            {
                _context.Update(oldRoute);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if(!_context.Marsrutai.Any(o => o.Id == route.Id))
                {
                    return NotFound();
                }
                throw;
            }
            TempData["SuccessMessage"] = "Maršruto aprašymas atnaujintas";
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> AddRouteObjects(int id)
        {
            if (_signInManager.IsSignedIn(User) &&
                _context.Marsrutai.FirstOrDefault(o => o.Id == id).FkRegistruotasVartotojas == int.Parse(_signInManager.UserManager.GetUserId(User)))
            {
                return View(await _context.Marsrutai.FirstOrDefaultAsync(o => o.Id == id));
            }
            else
            {
                return LocalRedirect("/");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddRouteObjects(int id, string[] address)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Address"] = address;
                return View(await _context.Marsrutai.FirstOrDefaultAsync(o => o.Id == id));
            }
            if (address.Length == 1)
            {
                if (address[0]==null)
                {
                    TempData["SuccessMessage"] = "Maršrutas išliko nepakeistas (objektai nebuvo nurodyti)";
                    return RedirectToAction(nameof(Index));
                }

            }
            List<JObject> convertedAdress = new List<JObject>();
            int index = 1;
            foreach (string add in address)
            {
                JObject obj = GetJsonAddress(add).Result;
                if (obj == null)
                {
                    ModelState.AddModelError(string.Empty, "Nepavyko konvertuoti " + index + " adreso");
                    ViewData["Address"] = address;
                    return View(await _context.Marsrutai.FirstOrDefaultAsync(o => o.Id == id));
                }
                if (obj.SelectToken("status").Value<string>() == "ZERO_RESULTS")
                {
                    ModelState.AddModelError(string.Empty, "Nepavyko konvertuoti " + index + " adreso");
                    ViewData["Address"] = address;
                    return View(await _context.Marsrutai.FirstOrDefaultAsync(o => o.Id == id));
                }
                convertedAdress.Add(obj);
                index++;
            }
            try
            {
                index = 1;
                foreach (JObject json in convertedAdress)
                {
                    string formatted_address = json.SelectToken("results[0].formatted_address").Value<string>();
                    LankytiniObjektai foundObject = _context.LankytiniObjektai.FirstOrDefault(o => o.Pavadinimas.Equals(formatted_address, StringComparison.OrdinalIgnoreCase));
                    LankytiniObjektai obj;
                    if (foundObject == null)
                    {
                        JToken country = GetCountry(json);
                        string countryShort = country.SelectToken("short_name").Value<string>();
                        Valstybes foundCountry = _context.Valstybes.FirstOrDefault(o => o.Trumpinys.Equals(countryShort, StringComparison.OrdinalIgnoreCase));
                        if (foundCountry == null)
                        {
                            Valstybes newCountry = new Valstybes();
                            newCountry.Pavadinimas = country.SelectToken("long_name").Value<string>();
                            newCountry.Trumpinys = countryShort;
                            newCountry.Zemynas = GetContinent(countryShort);
                            _context.Valstybes.Add(newCountry);
                            _context.SaveChanges();
                            int fk_Country = newCountry.Id;

                            LankytiniObjektai newObject = new LankytiniObjektai();
                            newObject.Pavadinimas = formatted_address;
                            newObject.XKoordinate = json.SelectToken("results[0].geometry.location.lng").Value<double>();
                            newObject.YKoordinate = json.SelectToken("results[0].geometry.location.lat").Value<double>();
                            newObject.FkValstybe = fk_Country;
                            _context.LankytiniObjektai.Add(newObject);
                            _context.SaveChanges();
                            obj = newObject;

                        }
                        else
                        {
                            LankytiniObjektai newObject = new LankytiniObjektai();
                            newObject.Pavadinimas = formatted_address;
                            newObject.XKoordinate = json.SelectToken("results[0].geometry.location.lng").Value<double>();

IS_Turizmas/Views/Routes/AddRouteObjects.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IS_Turizmas.Models.Marsrutai
@{
    ViewData["Title"] = "Pridėti maršruto objektus";
    <div class="container-fluid">
        <div class="col-md-10 mx-auto text-center py-3 my-3">
            <h4>Maršruto objektų redagavimas</h4>
            <h5>Maršrutas: @Html.DisplayFor(m => Model.Pavadinimas)</h5>
        </div>
        <div class="row">
            <div class="col-md-10 mx-auto">
                <form asp-controller="Routes" asp-action="AddRouteObjects" asp method="POST">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" name="Id" value="@Model.Id" />
                    <label><strong>Objektai(-as)</strong></label>
                    <ul>
                        @if (ViewData["Address"] != null)
                        {
                            @for (int i = 0; i < (ViewData["Address"] as string[]).Length; i++)
                            {
                                <li @if (i + 1 == (ViewData["Address"] as string[]).Length) { <text> class="last-object-row object-row form-group" </text>  } else { <text> class="object-row form-group" </text> }>

                                    <div class="row">
                                        <div class="col-md-9 mx-auto">
                                            <input type="text" class="form-control" name="address[]" placeholder="Įveskite adresą" value="@((ViewData["Address"] as string[])[i])" />
                                        </div>
                                        <div class="col-md-3 mx-auto">
                                            <button type="button" data-value="object-row" data-hide="add-more" data-last="last-object-row" class="btn btn-primary remove-row">-</button>
                                            <button type="button" data-value="last-object-row" data-hide="add-more" class="btn btn-primary add-more">+</button>
                                        </div>
                                    </div>
                                </li>
                            }
                        }
                        else
                        {
                            <li class="last-object-row object-row form-group">
                                <div class="row">
                                    <div class="col-md-9 mx-auto">
                                        <input type="text" class="form-control" name="address[]" placeholder="Įveskite adresą" />
                                    </div>
                                    <div class="col-md-3 mx-auto">
                                        <button type="button" data-value="object-row" data-hide="add-more" data-last="last-object-row" class="btn btn-primary remove-row">-</button>
                                        <button type="button" data-value="last-object-row" data-hide="add-more" class="btn btn-primary add-more">+</button>
                                    </div>
                                </div>
                            </li>
                        }
                    </ul>
                    <button class="btn btn-primary" type="submit">Pridėti objektus</button>
                </form>
            </div>
        </div>
        <br>
    </div>
}
@section Scripts{
    <script src="@Url.Content("~/js/object-row-manipulation.js")"></script>
}

IS_Turizmas/Views/Routes/CalculateRouteUniqueness.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using IS_Turizmas.Models
@model List<IS_Turizmas.Models.Marsrutai>
@{
    ViewData["Title"] = "Maršruto unikalumo indeksas";
    <div class="row mx-auto my-3 py-3">
        <div class="col-md-10 mx-auto text-center">
            <h4>Maršruto geografinis unikalumas</h4>
        </div>
    </div>
    <div class="row mx-auto">
        <div class="col-md-10 mx-auto">
            <form method="POST" asp-action="CalculateUniquenessIndex">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @if (Model.Count == 0)
                {
                    <p>Deja, neturite sukūrę jokių maršrutų</p>
                }
                else
                {
                    <div class="form-group">
                        <label><strong>Pasirinkite maršrutą</strong></label>
                        <select class="form-control" name="route">
                            @foreach (Marsrutai m in Model)
                            {
                                @if (m.Id.ToString().Equals(TempData["RouteID"])) {<option selected value="@m.Id">@Html.DisplayFor(model => m.Pavadinimas)</option>}
                                else { <option value="@m.Id">@Html.DisplayFor(model => m.Pavadinimas)</option>}
                            }
                        </select>
                    </div>
                    @if (TempData["StartDate"] == null)
                    {
                        <div class="row mx-auto px-4">
                            <label for="intervalChecked">Nurodyti lyginimo intervalą</label>
                            <input class="form-check-input" type="checkbox" id="intervalChecked" name="intChecked" data-toggle="collapse" href="#interval">
                        </div>
                        <div class="form-group collapse" id="interval">
                            <label><strong>Nurodykite maršruto sukūrimo intervalą</strong></label>
                            <div class="row input-daterange">
                                <div class="col-md-6">
                                    <label>Nuo</label>
                                    <input type="text" class="form-control" name="start" placeholder="Pasirinkite pradžios datą" />
                                </div>
                                <div class="col-md-6">
                                    <label>Iki</label>
                                    <input type="text" class="form-control" name="end" placeholder="Pasirinkite pabaigos datą" />
                                </div>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="row mx-auto px-4">
                            <label for="intervalChecked">Nurodyti lyginimo intervalą</label>
                            <input class="form-check-input" type="checkbox" id="intervalChecked" name="intChecked" data-toggle="collapse" href="#interval" checked aria-expanded="true">
                        </div>
                        <div class="form-group collapse show" id="interval">
                            <label><strong>Nurodykite maršruto sukūrimo intervalą</strong></label>
                            <div class="row input-daterange">
                                <div class="col-md-6">
                                    <label>Nuo</label>
                                    <input type="text" class="form-control" name="start" placeholder="Pasirinkite pradžios datą" />
                                </div>
                                <div class="col-md-6">
                                    <label>Iki</label>
                                    <input type="text" class="form-control" name="end" placeholder="Pasirinkite pabaigos datą" />
                                </div>
                            </div>
                        </div>
                    }
                }
                <div>
                    @if (Model.Count > 0)
                    {
                        <button class="btn btn-primary" type="submit">Skaičiuoti</button>
                    }
                    <a class="btn btn-primary" type="button" asp-action="Index">Grįžti</a>
                </div>
            </form>
            @if (TempData["UniquenessIndex"] != null)
            {
                <div class="my-3" id="score">
                    <label><strong>Rezultatas:</strong></label>
                    @if (TempData["StartDate"] != null)
                    {
                        <p>Lyginimo intervalas: @(((DateTime)TempData["StartDate"]).ToShortDateString())-@(((DateTime)TempData["EndDate"]).ToShortDateString())</p>
                    }
                    <p>Lyginta su @TempData["RouteCount"] maršrutų(-ais)</p>
                    <p>Maršrutas padengia @Html.Raw(TempData["UniquenessIndex"])% unikalaus ploto</p>
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width:@TempData["UniquenessIndex"]%" aria-valuenow="@TempData["UniquenessIndex"]%" aria-valuemin="0" aria-valuemax="100">@TempData["UniquenessIndex"]%</div>
                    </div>
                </div>
            }
        </div>
    </div>
}

IS_Turizmas/Views/Routes/CreateRouteDescription.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using IS_Turizmas.Models
@model IS_Turizmas.Models.Marsrutai
@{
    ViewData["Title"] = "Maršruto aprašymo kūrimas";
    <div class="container-fluid">
        <div class="col-md-10 mx-auto py-3 my-3">
            <h4 class="text-center">Maršruto aprašymo kūrimas</h4>
        </div>
        <div class="row">
            <div class="col-md-10 mx-auto">
                <form asp-controller="Routes" asp-action="CreateDescription" method="POST">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label><strong>Pavadinimas</strong></label>
                        <input type="text" class="form-control" asp-for="Pavadinimas" placeholder="Įveskite maršruto pavadinimą" />
                        <span asp-validation-for="Pavadinimas" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label><strong>Aprašymas</strong></label>
                        <textarea class="form-control" asp-for="Aprasymas" placeholder="Įveskite maršruto aprašymą"></textarea>
                        <span asp-validation-for="Aprasymas" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label><strong>Laiko įvertis</strong></label>
                        <select class="form-control" asp-for="LaikoIvertis">
                            @foreach (LaikoIverciai ivertis in ViewBag.LaikoIverciai)
                            {
                                <option value="@ivertis.Id">@ivertis.Name</option>
                            }
                        </select>
                        <span asp-validation-for="LaikoIvertis" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label><strong>Išlaidos</strong></label>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Nuo</label>
                                <input type="text" class="form-control" asp-for="IslaidosNuo" placeholder="Įveskite išlaidų minimumą" />
                                <span asp-validation-for="IslaidosNuo" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Iki</label>
                                <input type="text" class="form-control" asp-for="IslaidosIki" placeholder="Įveskite išlaidų maksimumą" />
                                <span asp-validation-for="IslaidosIki" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Sukurti</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

IS_Turizmas/Views/Routes/EditRouteDescription.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using IS_Turizmas.Models
@model IS_Turizmas.Models.Marsrutai
@{
    ViewData["Title"] = "Maršruto aprašymo redagavimas";
    <div class="container-fluid">
        <div class="col-md-10 mx-auto py-3 my-3">
            <h4 class="text-center">Maršruto aprašymo redagavimas</h4>
        </div>
        <div class="row">
            <div class="col-md-10 mx-auto">
                <form asp-controller="Routes" asp-action="EditDescription" method="POST">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label><strong>Pavadinimas</strong></label>
                        <input type="text" class="form-control" asp-for="Pavadinimas" placeholder="Įveskite maršruto pavadinimą" />
                        <span asp-validation-for="Pavadinimas" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label><strong>Aprašymas</strong></label>
                        <textarea class="form-control" asp-for="Aprasymas" placeholder="Įveskite maršruto aprašymą"></textarea>
                        <span asp-validation-for="Aprasymas" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label><strong>Laiko įvertis</strong></label>
                        <select class="form-control" asp-for="LaikoIvertis">
                            @foreach (LaikoIverciai ivertis in ViewBag.LaikoIverciai)
                            {
                                <option value="@ivertis.Id">@ivertis.Name</option>
                            }
                        </select>
                        <span asp-validation-for="LaikoIvertis" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label><strong>Išlaidos</strong></label>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Nuo</label>
                                <input type="text" class="form-control" asp-for="IslaidosNuo" placeholder="Įveskite išlaidų minimumą" />
                                <span asp-validation-for="IslaidosNuo" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label>Iki</label>
                                <input type="text" class="form-control" asp-for="IslaidosIki" placeholder="Įveskite išlaidų maksimumą" />
                                <span asp-validation-for="IslaidosIki" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Atnaujinti</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

IS_Turizmas/Views/Routes/EditRouteObjects.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IS_Turizmas.Models.Marsrutai 
@{
    ViewData["Title"] = "Redaguoti maršruto objektus";
    <div class="container-fluid">
        <div class="col-md-10 mx-auto text-center py-3 my-3">
            <h4>Maršruto objektų redagavimas</h4>
            <h5>Maršrutas: @Html.DisplayFor(m => Model.Pavadinimas)</h5>
        </div>
        <div class="row">
            <div class="col-md-10 mx-auto">
                <form asp-controller="Routes" asp-action="EditRouteObjects" asp method="POST">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" name="Id" value="@Model.Id"/>
                    <label><strong>Objektai(-as)</strong></label>
                    <ul>
                        @for (int i = 0; i < (ViewData["Address"] as string[]).Length; i++)
                        {
                            <li @if (i + 1 == (ViewData["Address"] as string[]).Length) { <text>class="last-object-row object-row form-group"</text> } else { <text>class="object-row form-group"</text> }>

                            <div class="row">
                                    <div class="col-md-9 mx-auto">
                                        <input type="text" class="form-control" name="address[]" placeholder="Įveskite adresą" value="@((ViewData["Address"] as string[])[i])"/>
                                    </div>
                                    <div class="col-md-3 mx-auto">
                                        <button type="button" data-value="object-row" data-hide="add-more" data-last="last-object-row" class="btn btn-primary remove-row">-</button>
                                        <button type="button" data-value="last-object-row" data-hide="add-more" 
                                                @if (i + 1 == (ViewData["Address"] as string[]).Length) {<text>class="btn btn-primary add-more"</text>} else{<text>class="btn btn-primary add-more d-none"</text>}>+</button>
                                    </div>
                                </div>
                            </li>
                        }
                    </ul>
                    <button class="btn btn-primary" type="submit">Keisti objektus</button>
                </form>
            </div>
        </div>
        <br>
    </div>
}
@section Scripts{
    <script src="@Url.Content("~/js/object-row-manipulation.js")"></script>
}

IS_Turizmas/Views/Routes/ViewMap.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<IS_Turizmas.Models.MarsrutoObjektai>
@{
    ViewData["Title"] = "Žemėlapis";
    <div class="row mx-auto my-3 py-3">
        <div class="col-md-10 mx-auto text-center">
            <h4>@Html.DisplayFor(m=>Model[0].FkMarsrutasNavigation.Pavadinimas)</h4>
        </div>
    </div>
    <div class="row mx-auto">
        <div class="col-md-10 mx-auto">
            <p><strong>Maršruto objektai:</strong></p>
            <ol>
                @for (var i = 0; i < Model.Count; i++)
                {
                <li>@Html.DisplayFor( m => Model[i].FkLankytinasObjektasNavigation.Pavadinimas) 
                <text>(@Model[i].FkLankytinasObjektasNavigation.FkValstybeNavigation.Trumpinys, @Model[i].FkLankytinasObjektasNavigation.FkValstybeNavigation.Zemynas)</text></li>
                }
            </ol>
        </div>
    </div>
    <div class="row mx-auto">
        <div class="col-md-10 mx-auto embeded-responsive embed-responsive-1by1 border rounded py-1 px-1 text-center">
            <iframe width="100%" height="500em" class="embed-responsive-item" frameborder="0"
                    src="@ViewBag.MapLink" allowfullscreen>
            </iframe>
        </div>
    </div>
    <br />
}