IS_Turizmas/Controllers/ContentController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using IS_Turizmas.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace IS_Turizmas.Controllers
{
    public class ContentController : HomeController
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<RegistruotiVartotojai> _signInManager;
        public ContentController(ApplicationDbContext context,
            SignInManager<RegistruotiVartotojai> signInManager):base(context)
        {
            _context = context;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> ViewAllRoutes()
        {
            return View(await _context.Marsrutai.Include(o => o.FkRegistruotasVartotojasNavigation)
                .Include(b => b.Reitingai).Include(o => o.MarsrutoObjektai).ToListAsync());
        }


        private void FetchAllData()
        {

        }

        public async Task<IActionResult> ViewRouteInfo(int id)
        {
            //ViewBag.URL = "https://localhost:44390"+Request.Path;
            ViewBag.URL = "https://www.makalius.lt/";
            int test = id;
            ViewBag.route_points = _context.MarsrutoObjektai.Include(o => o.FkLankytinasObjektasNavigation)
                .Where(o => o.FkMarsrutas == id).OrderBy(o => o.EilesNr).Select(o => o.FkLankytinasObjektasNavigation.Pavadinimas).ToArray();
            ViewBag.comments = _context.Komentarai.Where(o => o.FkMarsrutas == id).Select(y => y.Tekstas).ToArray();
            //var routeObjects = _context.MarsrutoObjektai.Where(o => o.FkMarsrutas == id);
            //var routeObjNames = 
            //ViewBag.RouteObjects = _context.LankytiniObjektai.Where(o => o.MarsrutoObjektai. )
            //ViewBag.RouteObjects = _context.MarsrutoObjektai.Where(o => o.FkMarsrutas == id);
            return View(await _context.Marsrutai.Include(o => o.FkRegistruotasVartotojasNavigation)
                .Include(b => b.Reitingai).FirstOrDefaultAsync(o => o.Id == id));
        }



        public IActionResult ViewAllRouteAnalysis()
        {
            //int MaxUpToPrice = _context.Marsrutai.Max(o => o.IslaidosIki);
            //ViewBag.HighestUpToPricesRoutes = _context.Marsrutai.Where(ob => ob.IslaidosIki == MaxUpToPrice).ToList();

            int LowestPrice = _context.Marsrutai.Min(o => o.IslaidosNuo);
            ViewBag.LowestPricesRoutes = _context.Marsrutai.Where(ob => ob.IslaidosNuo == LowestPrice).ToList();

            var allCountries = _context.Valstybes.ToList();
            //int hasMostCountriesCount = 0;
            List<DataPoint> dataPoints = new List<DataPoint>();

            foreach (var item in allCountries)
            {
                var foundCount = _context.Marsrutai.Where(
                obj => obj.MarsrutoObjektai.Any(
                    b => b.FkLankytinasObjektasNavigation.FkValstybeNavigation.Id == item.Id)).Count();

                dataPoints.Add(new DataPoint(item.Pavadinimas, foundCount));

                //if (foundCount> hasMostCountriesCount)
                //{
                //    hasMostCountriesCount = foundCount;
                //    ViewBag.MostPopularCountry = item.Pavadinimas;
                //}
            }




            

            //dataPoints.Add(new DataPoint("USA", 121));
            //dataPoints.Add(new DataPoint("Great Britain", 67));
            //dataPoints.Add(new DataPoint("China", 70));
            //dataPoints.Add(new DataPoint("Russia", 56));
            //dataPoints.Add(new DataPoint("Germany", 42));
            //dataPoints.Add(new DataPoint("Japan", 41));
            //dataPoints.Add(new DataPoint("France", 42));
            //dataPoints.Add(new DataPoint("South Korea", 21));

            ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);




            //ViewBag.searchedRoutes = _context.Marsrutai.Where(obj => obj.MarsrutoObjektai.Any
            //(b => b.FkLankytinasObjektasNavigation.FkValstybeNavigation.Id == countryId)).ToList();
            return View();
        }

        public async Task<IActionResult> FilterRoutes()
        {
            ViewBag.Valstybes = _context.Valstybes.ToList();
            return View();
        }





        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult FoundFilterRoutes(string filterCountry)
        {
            int countryId = Int32.Parse(filterCountry);            
            ViewBag.searchedRoutes = _context.Marsrutai.Include(o => o.FkRegistruotasVartotojasNavigation).Include(b => b.Reitingai)
            .Where(obj => obj.MarsrutoObjektai.Any(b => b.FkLankytinasObjektasNavigation.FkValstybeNavigation.Id == countryId)).ToList();
            return View();
        }

        public async Task<IActionResult> searchRoutes()
        {
            ViewBag.Valstybes = _context.Valstybes.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FoundRoutes(string searchText, string filterCountry)
        {
            if (searchText == null)
            {
                TempData["ErrorMessage"] = "Paieškos žodis yra privalomas";
                return RedirectToAction("searchRoutes");
            }
            if (filterCountry == "Jokio")
            {
                ViewBag.searchedRoutes = _context.Marsrutai
            .Include(o => o.FkRegistruotasVartotojasNavigation).Include(b => b.Reitingai)
            .Where(obj => EF.Functions.Like(obj.Pavadinimas, "%" + searchText + "%")).ToList();
            }
            else
            {
                int countryId = Int32.Parse(filterCountry);
                ViewBag.searchedRoutes = _context.Marsrutai
            .Include(o => o.FkRegistruotasVartotojasNavigation).Include(b => b.Reitingai)
            .Where(obj => EF.Functions.Like(obj.Pavadinimas, "%" + searchText + "%"))
            .Where(obj => obj.MarsrutoObjektai.Any(b => b.FkLankytinasObjektasNavigation.FkValstybeNavigation.Id == countryId)).ToList();
            }            
            return View();
            //return View(await _context.Marsrutai.Where(obj => EF.Functions.Like(obj.Pavadinimas, "%" + searchText + "%")).ToListAsync);
        }

        public IActionResult ShareRoute()
        {
            return View();
        }

        public async Task<IActionResult> Rate(int Id)
        {
            ViewBag.id = Id;

            bool auth = _signInManager.Context.User.Identity.IsAuthenticated;

            if (!auth)
            {
                TempData["ErrorMessage"] = "Kad suteiktumėte reitingą, turite prisijungti.";
                return RedirectToAction("ViewRouteInfo", new { id = Id });
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LeaveRating([Bind("Reitingas, FkMarsrutas")] Reitingai rating)
        {
            int userId = Int32.Parse(_signInManager.UserManager.GetUserId(this.User));
            int routeId = rating.FkMarsrutas;

            var existingRating = _context.Reitingai.Where(o => o.FkMarsrutas == routeId
            && o.FkRegistruotasVartotojas == userId).FirstOrDefault();

            if (existingRating == null)
            {
                rating.Data = DateTime.Now;
                rating.FkRegistruotasVartotojas = userId;
                try
                {
                    _context.Reitingai.Add(rating);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                    throw;
                }                
            } else
            {
                var oldRating = _context.Reitingai.Find(existingRating.Id);
                oldRating.Data = DateTime.Now;
                oldRating.Reitingas = rating.Reitingas;
                try
                {
                    _context.Reitingai.Update(oldRating);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                    throw;
                }
            }
            TempData["SuccessMessage"] = "Reitingas pateiktas";
            return RedirectToAction("ViewRouteInfo", new { id = routeId });
        }


        public async Task<IActionResult> Comment(int Id)
        {
            ViewBag.id = Id;

            bool auth = _signInManager.Context.User.Identity.IsAuthenticated;

            if (!auth)
            {
                TempData["ErrorMessage"] = "Kad rašytumėte komentarą, turite prisijungti.";
                return RedirectToAction("ViewRouteInfo", new { id = Id });
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateComment([Bind("Tekstas, FkMarsrutas")] Komentarai comment)
        {
            int routeId = comment.FkMarsrutas;
            if (comment.Tekstas == null)
            {
                TempData["ErrorMessage"] = "Jūs neparašėte komentaro";
                return RedirectToAction("ViewRouteInfo", new { id = routeId });
            }

            int userId = Int32.Parse(_signInManager.UserManager.GetUserId(this.User));

            comment.Data = DateTime.Now;
            comment.FkRegistruotasVartotojas = userId;
                     


            try
            {
                _context.Komentarai.Add(comment);
                await _context.SaveChangesAsync();
            }
            catch(DbUpdateConcurrencyException)
            {
                return NotFound();

IS_Turizmas/Views/Content/Comment.cshtml
@using IS_Turizmas.Models
@model IS_Turizmas.Models.Komentarai
@{
    ViewData["Title"] = "Comment";
    <div class="col-md-10 mx-auto text-center py-3 my-3">
        <h1>Komentavimo langas</h1>
    </div>

    <div class="col-md-10 mx-auto">
        <form asp-controller="Content" asp-action="CreateComment" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>            
            <div class="form-group">
                <label for="comment">Parašykite komentarą</label>
                <textarea asp-for="Tekstas" class="form-control" id="comment" rows="3"></textarea>
                <span asp-validation-for="Tekstas" class="text-danger"></span>
                <input type="hidden" asp-for="FkMarsrutas" value=@ViewBag.id />
            </div>
            <div>
                <button type="submit" class="btn btn-primary">Sukurti</button>
            </div>
        </form>
        <div class="my-2">
            <a asp-controller="Content" asp-action="ViewRouteInfo" asp-route-id="@ViewBag.id" class="btn btn-primary">Atgal</a>
        </div>
    </div>
}

IS_Turizmas/Views/Content/FilterRoutes.cshtml
@using IS_Turizmas.Models
@model IS_Turizmas.Models.Marsrutai
@{
    ViewData["Title"] = "FilterRoutes";
    <div class="col-md-10 mx-auto text-center py-3 my-3">
        <h1>Maršrutų paieška pagal filtrą</h1>
    </div>


    <div class="col-md-10 mx-auto">
        <h3>Paieška pagal šalį</h3>
        <form asp-controller="Content" asp-action="FoundFilterRoutes" method="POST">
            <div class="form-group">
                <label for="searchCountry">Pasirinkite šalį</label>
                <select class="form-control" name="filterCountry">
                    @foreach (Valstybes valstybe in ViewBag.Valstybes)
                    {
                        <option value="@valstybe.Id">@valstybe.Pavadinimas</option>
                    }
                </select>
                <input class="btn btn-primary" value="Filtruoti" type="submit" />
            </div>
        </form>
    </div>
}

IS_Turizmas/Views/Content/FoundFilterRoutes.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using IS_Turizmas.Models
@model List<IS_Turizmas.Models.Marsrutai>
@{
    ViewData["Title"] = "FoundRoutes";
    <div class="col-md-10 mx-auto text-center py-3 my-3">
        <h1>Visų sistemos maršrutų langas</h1>
    </div>
    @if (ViewBag.searchedRoutes.Count > 0)
    {
        <div class="col-md-10 mx-auto">
            <table class="table table-striped text-center">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Pavadinimas</th>
                        <th scope="col">Sukūrimo data</th>
                        <th scope="col">Reitingas</th>
                        <th scope="col">Autorius</th>
                        <th scope="col">Veiksmai</th>
                    </tr>
                </thead>
                <tbody>
                    @for (var i = 0; i < ViewBag.searchedRoutes.Count; i++)
                    {
                        <tr>
                            <th>@(i + 1)</th>
                            <td>@ViewBag.searchedRoutes[i].Pavadinimas</td>
                            @{ string formatedValue = ViewBag.searchedRoutes[i].SukurimoData.ToShortDateString(); }
                            <td>@Html.DisplayFor(model => formatedValue)</td>
                            <td>@ViewBag.searchedRoutes[i].GetRatingAverage()</td>
                            <td>
                                <a asp-action="Index" asp-controller="User" asp-route-id="@ViewBag.searchedRoutes[i].FkRegistruotasVartotojasNavigation.Id">
                                    @ViewBag.searchedRoutes[i].FkRegistruotasVartotojasNavigation.Vardas
                                    @ViewBag.searchedRoutes[i].FkRegistruotasVartotojasNavigation.Pavarde
                                </a>
                            </td>
                            <td>
                                <a asp-controller="Content" asp-action="ViewRouteInfo"
                                   asp-route-id="@ViewBag.searchedRoutes[i].Id">Maršruto informacija</a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    }
    else
    {
        <h3 class="mx-auto text-center">Maršrutų rasti nepavyko</h3>
    }
}

IS_Turizmas/Views/Content/FoundRoutes.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using IS_Turizmas.Models
@model List<IS_Turizmas.Models.Marsrutai>
@{
    ViewData["Title"] = "FoundRoutes";
    <div class="col-md-10 mx-auto text-center py-3 my-3">
        <h1>Visų sistemos maršrutų langas</h1>
    </div>
    @if (ViewBag.searchedRoutes.Count > 0)
    {
        <div class="col-md-10 mx-auto">
            <table class="table table-striped text-center">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Pavadinimas</th>
                        <th scope="col">Sukūrimo data</th>
                        <th scope="col">Reitingas</th>
                        <th scope="col">Autorius</th>
                        <th scope="col">Veiksmai</th>
                    </tr>
                </thead>
                <tbody>
                @for (var i = 0; i < ViewBag.searchedRoutes.Count; i++)
                {
                    <tr>
                        <th>@(i + 1)</th>
                        <td>@ViewBag.searchedRoutes[i].Pavadinimas</td>
                        @{ string formatedValue = ViewBag.searchedRoutes[i].SukurimoData.ToShortDateString(); }
                        <td>@Html.DisplayFor(model => formatedValue)</td>
                        <td>@ViewBag.searchedRoutes[i].GetRatingAverage()</td>
                        <td>
                            <a asp-action="Index" asp-controller="User" asp-route-id="@ViewBag.searchedRoutes[i].FkRegistruotasVartotojasNavigation.Id">
                                @ViewBag.searchedRoutes[i].FkRegistruotasVartotojasNavigation.Vardas
                                @ViewBag.searchedRoutes[i].FkRegistruotasVartotojasNavigation.Pavarde
                            </a>
                        </td>
                        <td><a asp-controller="Content" asp-action="ViewRouteInfo"
                            asp-route-id="@ViewBag.searchedRoutes[i].Id">Maršruto informacija</a></td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    }
    else
    {
        <h3 class="mx-auto text-center">Maršrutų rasti nepavyko</h3>
    }

}

IS_Turizmas/Views/Content/Rate.cshtml
@using IS_Turizmas.Models
@model IS_Turizmas.Models.Reitingai
@{
    ViewData["Title"] = "Rate";
    <div class="col-md-10 mx-auto text-center py-3 my-3">
        <h1>Reitingavimo langas</h1>
    </div>


    <div class="col-md-10 mx-auto">
        <form class="my-2" asp-controller="Content" asp-action="LeaveRating" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="rating">Pasirinkite reitingą</label>
                <select asp-for="Reitingas" class="form-control" id="rating">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
                <span asp-validation-for="Reitingas" class="text-danger"></span>
                <input type="hidden" asp-for="FkMarsrutas" value=@ViewBag.id />
            </div>
            <div>
                <button type="submit" class="btn btn-primary">Palikti reitingą</button>
            </div>
        </form>
        <a asp-controller="Content" asp-action="ViewRouteInfo" asp-route-id="@ViewBag.id" class="btn btn-primary">Atgal</a>
    </div>
}

IS_Turizmas/Views/Content/SearchRoutes.cshtml
@model List<IS_Turizmas.Models.Marsrutai>
@using IS_Turizmas.Models
@{
    ViewData["Title"] = "SearchRoutes";
    <div class="col-md-10 mx-auto text-center py-3 my-3">
        <h1>Maršrutų paieška pagal raktažodį</h1>
        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
        }
    </div>


    <div class="col-md-10 mx-auto">

        <form asp-controller="Content" asp-action="FoundRoutes" method="POST">
            <div class="form-group">
                <label for="searchKey">Paieškos tekstas (privalomas)</label>
                <input type="text" class="form-control" id="searchKey" name="searchText" placeholder="Įveskite paieškos žodį">
                <label for="searchCountry">Paieškos geografinis regionas (neprivalomas)</label>
                <select id="searchCountry" class="form-control" name="filterCountry">
                    <option>Jokio</option>
                    @foreach (Valstybes valstybe in ViewBag.Valstybes)
                    {
                        <option value="@valstybe.Id">@valstybe.Pavadinimas</option>
                    }
                </select>
                <input class="btn btn-primary" value="Ieškoti" type="submit" />
            </div>
        </form>

    </div>
}

IS_Turizmas/Views/Content/ShareRoute.cshtml
@{
    ViewData["Title"] = "ShareRoute";
    <div class="col-md-10 mx-auto text-center py-3 my-3">
        <h1>Dalinimosi langas</h1>
    </div>
    <div class="col-md-10 mx-auto">
        <div class="row my-3 mx-auto">
            <div class="col-md-4 text-center">
                <a href="https://facebook.com"><img class="social-media" src="~/images/Social Media/facebook.png"/></a>
            </div>
            <div class="col-md-4 text-center">
                <a href="https://twitter.com"><img class="social-media" src="~/images/Social Media/twitter.png" /></a>
            </div>
            <div class="col-md-4 text-center">
                <a href="https://reddit.com"><img class="social-media" src="~/images/Social Media/reddit.png" /></a>
            </div>
        </div>
        <div class="row py-3">
        <a asp-controller="Content" asp-action="ViewRouteInfo" class="btn btn-primary">Atgal</a>
        </div>
    </div>

}

IS_Turizmas/Views/Content/ViewAllRouteAnalysis.cshtml
@using IS_Turizmas.Models
@model IS_Turizmas.Models.Reitingai
@{
    <script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	theme: "light2", // "light1", "dark1", "dark2"
	exportEnabled: true,
	title: {
		text: "Sukurtų maršrutų skaičius atskirose valstybėse"
	},
	data: [{
		type: "column",
		dataPoints:  @Html.Raw(ViewBag.DataPoints)
	}]
});
chart.render();

}
    </script>

    ViewData["Title"] = "ViewAllRouteAnalysis";
    <div class="col-md-10 mx-auto text-center py-3 my-3">
        <h1>Visų maršrutų analizė</h1>
    </div>

    <div class="mx-auto" id="chartContainer" style="height: 370px; width: 80%;"></div>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>


    <div class="col-md-10 mx-auto">
        <table class="table table-striped text-center table-bordered">
            <h3>Pigiausi galimi maršrutai:</h3>
            <table class="table table-striped text-center">
                <thead>
                    <tr>
                        <th scope="col">Pavadinimas</th>
                        <th scope="col">Išlaidos nuo</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Marsrutai route in ViewBag.LowestPricesRoutes)
                    {
                        <tr>
                            <td>@Html.DisplayFor(model => route.Pavadinimas)</td>
                            <td>@Html.DisplayFor(model => route.IslaidosNuo) &#8364;</td>
                        </tr>
                    }
                </tbody>
            </table>

        </table>
    </div>
}

IS_Turizmas/Views/Content/ViewAllRoutes.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<IS_Turizmas.Models.Marsrutai>
@{
    ViewData["Title"] = "AllRoutes";
    <div class="col-md-10 mx-auto text-center py-3 my-3">
        <h1>Visų sistemos maršrutų langas</h1>
    </div>
    <div class="col-md-10 mx-auto">
        <table class="table table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Pavadinimas</th>
                    <th scope="col">Sukūrimo data</th>
                    <th scope="col">Reitingo vidurkis</th>
                    <th scope="col">Autorius</th>
                    <th scope="col">Veiksmai</th>
                </tr>
            </thead>
            <tbody>
                @for (var i = 0; i < Model.Count; i++)
                {
                    <tr>
                        <th>@(i+1)</th>
                        <td>@Html.DisplayFor(model => Model[i].Pavadinimas)</td>
                        @{ string formatedValue = Model[i].SukurimoData.ToShortDateString(); }
                        <td>@Html.DisplayFor(model => formatedValue)</td>
                        <td>@Model[i].GetRatingAverage()</td>
                        <td>
                            <a asp-action="Index" asp-controller="User" asp-route-id="@Model[i].FkRegistruotasVartotojasNavigation.Id">
                                @Model[i].FkRegistruotasVartotojasNavigation.Vardas
                                @Model[i].FkRegistruotasVartotojasNavigation.Pavarde
                            </a>
                        </td>
                        <td>
                            <a asp-controller="Content" asp-action="ViewRouteInfo" 
                               asp-route-id="@Model[i].Id">Maršruto informacija</a>
                        </td>
                    </tr>
                }                
            </tbody>
        </table>
    </div>
}

IS_Turizmas/Views/Content/ViewRouteInfo.cshtml
@model IS_Turizmas.Models.Marsrutai
@{
    ViewData["Title"] = "ViewRouteInfo";
    <div class="col-md-10 mx-auto text-center py-3 my-3">
        <h1>Maršruto informacija</h1>
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-success">@TempData["SuccessMessage"]</div>
        }
        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
        }
    </div>


    <div class="col-md-10 mx-auto">
        <table class="table table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">Pavadinimas</th>
                    <th scope="col">Kaina nuo</th>
                    <th scope="col">Kaina iki</th>
                    <th scope="col">Sukūrimo data</th>
                    <th scope="col">Reitingas</th>
                    <th scope="col">Autorius</th>
                    <th scope="col">Veiksmai</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Html.DisplayFor(model => Model.Pavadinimas)</td>
                    <td>@Model.IslaidosNuo &#8364;</td>
                    <td>@Model.IslaidosIki &#8364;</td>
                    @{ string formatedValue = Model.SukurimoData.ToShortDateString(); }
                    <td>@Html.DisplayFor(model => formatedValue)</td>
                    <td>@Model.GetRatingAverage()</td>
                    <td>
                        <a asp-action="Index" asp-controller="User" asp-route-id="@Model.FkRegistruotasVartotojasNavigation.Id">
                            @Model.FkRegistruotasVartotojasNavigation.Vardas
                            @Model.FkRegistruotasVartotojasNavigation.Pavarde
                        </a>
                    </td>
                    <td>
                        <div class="fb-share-button d-inline-block" data-href=@ViewBag.URL data-layout="button" data-size="large">
                            <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fmakaliai-fake.lt%2F&amp;src=sdkpreparse" 
                           class="fb-xfbml-parse-ignore">Bendrinti</a>
                        </div>
                        <a class="d-inline-block" asp-action="Comment" asp-route-id="@Model.Id">Rašyti komentarą</a>
                        <a class="d-inline-block" asp-action="Rate" asp-route-id="@Model.Id">Suteikti reitingą</a>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="row">
            <h3>Aprašymas</h3>
            <div class="col-12 my-3">
                <p>@Model.Aprasymas</p>
            </div>
            <h3>Maršruto objektai</h3>
            <div class="col-12">
                <ol>
                    @foreach (var item in ViewBag.route_points)
                    {
                        <li>@item</li>
                    }
                </ol>
            </div>
            <h3>Komentarai</h3>

            @foreach (var item in ViewBag.comments)
            {
                <div class="col-12 border rounded">
                    <p>@item</p>
                </div>
            }
                
        </div>
    </div>
    <br />
}