IS_Turizmas/Controllers/AdvertsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using IS_Turizmas.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IS_Turizmas.Controllers
{
    public class AdvertsController : HomeController
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<RegistruotiVartotojai> _signInManager;
        private readonly IWebHostEnvironment _env;
        public AdvertsController(ApplicationDbContext context, SignInManager<RegistruotiVartotojai> signInManager,
            IWebHostEnvironment env):base(context)
        {
            _context = context;
            _signInManager = signInManager;
            _env = env;

        }

        //Is it good???
        public async Task<IActionResult> GetRandomAdvert()
        {
            var advert_plans = await _context.ReklamosPlanai.Include(o => o.ReklamavimoLaikai).Where(o=> o.Laikas_nuo < DateTime.Now && o.Laikas_iki > DateTime.Now).ToListAsync();
            int sum = 0;
            Random random = new Random();
            foreach (ReklamosPlanai rp in advert_plans)
            {
                sum = sum + (int)rp.Kaina;
            }
            int r = random.Next(0, sum);
            foreach (ReklamosPlanai rp in advert_plans)
            {
                sum = sum - (int)rp.Kaina;
                if (sum <= 0)
                {
                    return View(await _context.Reklamos.Where(o => o.Id == rp.FkReklama).ToListAsync());
                }
            }
            return LocalRedirect("/");
        }
        public IActionResult Confirm()
        {
            return View();
        }

        public IActionResult ConfirmDelete()
        {
            return View();
        }
        public async Task<IActionResult> AdvertList()
        {
            var userId = _signInManager.UserManager.GetUserId(User);
            if (userId == null || !User.IsInRole("Verslo"))
            {
                return LocalRedirect("/");
            }
            int id = int.Parse(userId);
            return View(await _context.Reklamos.Where(o => o.FkVersloVartotojas == id).ToListAsync());
        }
        public IActionResult CreateAdvert()
        {
            if (_signInManager.IsSignedIn(User) && User.IsInRole("Verslo"))
            {
                return View();
            }
            else
            {
                return LocalRedirect("/");
            }
        }

        public IActionResult CreateAdvertPlan()
        {
            return View();
        }
        public async Task<IActionResult> DeleteAdvertPlan()
        {
            var userId = _signInManager.UserManager.GetUserId(User);
            if (userId == null || !User.IsInRole("Verslo"))
            {
                return LocalRedirect("/");
            }
            int id = int.Parse(userId);
            ViewBag.ReklamosPlanai = _context.ReklamosPlanai.ToList();
            ViewBag.ReklamavimoLaikai = _context.ReklamavimoLaikai.ToList();
            return View(await _context.Reklamos.Include(o => o.ReklamosPlanai).Where(o => o.FkVersloVartotojas == id).ToListAsync());
        }

        public async Task<IActionResult> ViewAdvertStatistics(int id)
        {
            if (_signInManager.IsSignedIn(User) && User.IsInRole("Verslo") &&
                _context.Reklamos.FirstOrDefault(o => o.Id == id).FkVersloVartotojas == int.Parse(_signInManager.UserManager.GetUserId(User)))
            {
                return View(await _context.Reklamos.FirstOrDefaultAsync(o => o.Id == id));
            }
            else
            {
                return LocalRedirect("/");
            }
        }

        public async Task<IActionResult> EditAdvert(int id)
        {
            if (_signInManager.IsSignedIn(User) && User.IsInRole("Verslo") &&
                _context.Reklamos.FirstOrDefault(o => o.Id == id).FkVersloVartotojas == int.Parse(_signInManager.UserManager.GetUserId(User)))
            {
                return View(await _context.Reklamos.FirstOrDefaultAsync(o => o.Id == id));
            }
            else
            {
                return LocalRedirect("/");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ConfirmActivation()
        {
            return RedirectToAction(nameof(AdvertList));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AdvertCreate([Bind("Pavadinimas, Url")]
        Reklamos advert, IFormFile Paveikslelis)
        {
            if (!ModelState.IsValid)
            {
                return View("~/Views/Adverts/CreateAdvert.cshtml");
            }
            if (Paveikslelis == null)
            {
                ModelState.AddModelError("", "Paveikslėlis yra privalomas");
                return View("~/Views/Adverts/CreateAdvert.cshtml");
            }

            if (!IsImage(Paveikslelis))
            {
                ModelState.AddModelError("", "Paveikslėlis turi būti paveikslo tipo");
                return View("~/Views/Adverts/CreateAdvert.cshtml");
            }

            advert.Paspaudimai = 0;
            advert.FkVersloVartotojas = int.Parse(_signInManager.UserManager.GetUserId(User));

            string filename = advert.Pavadinimas + DateTime.Now.ToString("yyyy-dd-M--HH-mm-ss") + Path.GetExtension(Paveikslelis.FileName);
            var saveimg = Path.Combine(_env.WebRootPath, "images", "Adds", filename);
            var stream = new FileStream(saveimg, FileMode.Create);
            await Paveikslelis.CopyToAsync(stream);

            advert.Paveikslelis = "images/Adds/"+filename;
            
            try
            {
                _context.Reklamos.Add(advert);

                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return NotFound();
                throw;
            }
            TempData["SuccessMessage"] = "Reklama sukurta";
            return RedirectToAction(nameof(AdvertList));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AdvertPlanCreate()
        {
            return RedirectToAction(nameof(Confirm));
        }

        public IActionResult AdvertPlanDelete()
        {
            return RedirectToAction(nameof(ConfirmDelete));
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AdvertEdit(int id, [Bind("Id,Pavadinimas, Url")]
        Reklamos advert, IFormFile naujasPaveikslas)
        {
            if (id != advert.Id)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                return View("~/Views/Adverts/EditAdvert.cshtml");
            }
            if (naujasPaveikslas != null)
            {
                if (!IsImage(naujasPaveikslas))
                {
                    ModelState.AddModelError("", "Paveikslėlis turi būti paveikslo tipo");
                    return View("~/Views/Adverts/EditAdvert.cshtml");
                }
            }
            Reklamos oldAdvert = _context.Reklamos.Find(id);
            if (oldAdvert.FkVersloVartotojas != int.Parse(_signInManager.UserManager.GetUserId(User)))
            {
                return NotFound();
            }
            oldAdvert.Pavadinimas = advert.Pavadinimas;
            oldAdvert.Url = advert.Url;
            if (naujasPaveikslas != null)
            {
                var path = Path.Combine(_env.WebRootPath, oldAdvert.Paveikslelis);
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }

                string filename = advert.Pavadinimas + DateTime.Now.ToString("yyyy-dd-M--HH-mm-ss") + Path.GetExtension(naujasPaveikslas.FileName);
                var saveimg = Path.Combine(_env.WebRootPath, "images", "Adds", filename);
                var stream = new FileStream(saveimg, FileMode.Create);
                await naujasPaveikslas.CopyToAsync(stream);

                advert.Paveikslelis = "images/Adds/" + filename;
                oldAdvert.Paveikslelis = advert.Paveikslelis;
            }
            
            try
            {
                _context.Update(oldAdvert);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_context.Reklamos.Any(o => o.Id == advert.Id))
                {
                    return NotFound();
                }
                throw;
            }
            TempData["SuccessMessage"] = "Reklama atnaujinta";
            return RedirectToAction(nameof(AdvertList));
        }

        public IActionResult GoToAdLink(int id)
        {
            Reklamos reklama = this._context.Reklamos.Where(o=> o.Id==id).FirstOrDefault();
            reklama.Paspaudimai=reklama.Paspaudimai+1;
            _context.Update(reklama);
            _context.SaveChanges();
            return Redirect(reklama.Url);
        }

        private bool IsImage(IFormFile postedFile)
        {
            const int ImageMinimumBytes = 512;

            //-------------------------------------------
            //  Check the image mime types
            //-------------------------------------------
            if (postedFile.ContentType.ToLower() != "image/jpg" &&
                        postedFile.ContentType.ToLower() != "image/jpeg" &&
                        postedFile.ContentType.ToLower() != "image/pjpeg" &&

IS_Turizmas/Views/Adverts/AdvertList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<IS_Turizmas.Models.Reklamos>
@{
    ViewData["Title"] = "Mano reklamos";
    <div class="col-md-10 mx-auto text-center py-3 my-3">
        <h1>Mano reklamos</h1>
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-success">@TempData["SuccessMessage"]</div>
        }
    </div>
    <div class="col-md-10 mx-auto">
        <table class="table table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Pavadinimas</th>
                    <th scope="col">Veiksmai</th>
                </tr>
                <div class="col-md-10 mx-auto">
                    <div class="row">
                        <div class="col-md-4">
                            <a asp-action="CreateAdvert">Kurti reklamą</a>
                        </div>
                        <div class="col-md-4">
                            <a asp-action="CreateAdvertPlan">Kurti planą</a>
                        </div>
                        <div class="col-md-4">
                            <a asp-action="DeleteAdvertPlan">Mano planai</a>
                        </div>
                    </div>
                </div>
                @for (var i = 0; i < Model.Count; i++)
                {
            <tr>
                <td>@Html.DisplayFor(model => Model[i].Id)</td>
                <td>@Html.DisplayFor(model => Model[i].Pavadinimas)</td>
                <td><a asp-action="ViewAdvertStatistics" asp-route-id="@Model[i].Id">Reklamos statistika</a> | <a asp-action="EditAdvert" asp-route-id="@Model[i].Id">Redaguoti reklamą</a> | <a asp-action="Index" data-toggle="modal" data-target="#deleteConfirmation" asp-route-id="@Model[i].Id">Šalinti</a></td>
            </tr>
                }
            </thead>
        </table>
    </div>


    <!--Delete confirmation window-->
    <div class="modal fade" id="deleteConfirmation" tabindex="-1" role="dialog" aria-labelledby="Delete confirmation window" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteConfirmation">Šalinimo patvirtinimas</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Ar tikrai norite ištrinti reklamą?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Atšaukti</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Šalinti</button>
                </div>
            </div>
        </div>
    </div>
}

IS_Turizmas/Views/Adverts/Confirm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "PatvirtintiPatvirtintiPatvirtintiPatvirtintiPatvirtinti";
    <div class="container-fluid">
        <div class="col-md-10 mx-auto text-center py-3 my-3">
            <h1>Patvirtinti</h1>
        </div>
        <div class="row">
            <div class="col-md-10 mx-auto">
                <form asp-controller="Adverts" asp-action="ConfirmActivation" method="POST">
                    <div class="form-group">
                        <label><strong>Norėdami patvirtinti įrašykite žodi "Patvirtinti"</strong></label>
                        <input type="text" class="form-control" placeholder="Patvirtinti"/>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Patvirtinti</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

IS_Turizmas/Views/Adverts/ConfirmDelete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Patvirtinti plano pašalinimą";
    <div class="container-fluid">
        <div class="col-md-10 mx-auto text-center py-3 my-3">
            <h1>Patvirtinti</h1>
        </div>
        <div class="row">
            <div class="col-md-10 mx-auto">
                <form asp-controller="Adverts" asp-action="ConfirmActivation" method="POST">
                    <div class="form-group">
                        <label><strong>Norėdami pašalinti įrašykite žodi "Šalinti"</strong></label>
                        <input type="text" class="form-control" placeholder="Šalinti" />
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Šalinti</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

IS_Turizmas/Views/Adverts/CreateAdvert.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using IS_Turizmas.Models
@model IS_Turizmas.Models.Reklamos
@{
    ViewData["Title"] = "Kurti reklamą";

    <div class="container-fluid">
        <div class="col-md-10 mx-auto text-center py-3 my-3">
            <h1>Kuriama reklama</h1>
        </div>
        <div class="row">
            <div class="col-md-10 mx-auto">
                <form asp-controller="Adverts" asp-action="AdvertCreate" enctype="multipart/form-data" method="POST">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label><strong>Pavadinimas</strong></label>
                        <input type="text" class="form-control" asp-for="Pavadinimas" placeholder="Įveskite reklamos pavadinimą" />
                        <span asp-validation-for="Pavadinimas" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label><strong>Paveikslėlis</strong></label>
                        <input type="file" class="form-control" name="Paveikslelis" />
                    </div>
                    <div class="form-group">
                        <label><strong>Tikslo url</strong></label>
                        <input type="text" class="form-control" asp-for="Url" placeholder="Įveskite url" />
                        <span asp-validation-for="Url" class="text-danger"></span>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Sukurti</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

IS_Turizmas/Views/Adverts/CreateAdvertPlan.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Create Advert Plan";
    <div class="container-fluid">
        <div class="col-md-10 mx-auto text-center py-3 my-3">
            <h1>Kuriamas reklamos planas</h1>
        </div>
        <div class="row">
            <div class="col-md-10 mx-auto">
                <form asp-controller="Adverts" asp-action="AdvertPlanCreate" method="POST">
                    <div class="form-group">
                        <label><strong>Data iki</strong></label>
                        <input type="datetime-local" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label><strong>Laikas nuo</strong></label>
                        <input type="time" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label><strong>Laikas iki</strong></label>
                        <input type="time" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label><strong>Savaitės dienos</strong></label>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="MondayCheck">
                            <label class="form-check-label" for="MondayCheck">
                                Pirmadienis
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="TuesdayCheck">
                            <label class="form-check-label" for="TuesdayCheck">
                                Antradienis
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="WednesdayCheck">
                            <label class="form-check-label" for="WednesdayCheck">
                                Trečiadienis
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="ThursdayCheck">
                            <label class="form-check-label" for="ThursdayCheck">
                                Ketvirtadienis
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="FridayCheck">
                            <label class="form-check-label" for="FridayCheck">
                                Penktadienis
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="SaturdayCheck">
                            <label class="form-check-label" for="SaturdayCheck">
                                Šeštadienis
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="SundayCheck">
                            <label class="form-check-label" for="SundayCheck">
                                Sekmadienis
                            </label>
                        </div>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Sukurti</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <br/>
}

IS_Turizmas/Views/Adverts/DeleteAdvertPlan.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using IS_Turizmas.Models
@model List<IS_Turizmas.Models.Reklamos>
@{
    ViewData["Title"] = "Delete Advert Plan";
    <div class="col-md-10 mx-auto text-center py-3 my-3">
        <h1>Mano planai</h1>
    </div>
    <div class="col-md-10 mx-auto">
        <table class="table table-striped text-center">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Pavadinimas</th>
                    <th scope="col">Veiksmas</th>
                </tr>
                @for (var i = 0; i < Model.Count; i++)
                {
                    @if (Model[i].ReklamosPlanai.Count > 0)
                    {
                        <tr>
                            <td>@Html.DisplayFor(model => Model[i].Id)</td>
                            <td>@Html.DisplayFor(model => Model[i].Pavadinimas)</td>
                            <td>Šalinimas</td>
                        </tr>
                        @foreach (ReklamosPlanai planas in ViewBag.ReklamosPlanai)
                        {
                            @if (planas.FkReklama == Model[i].Id)
                            {
                                <tr>
                                    <td>Nuo: @planas.Laikas_nuo</td>
                                    <td>Iki: @planas.Laikas_iki</td>
                                    <td><a asp-action="AdvertPlanDelete" asp-route-id="@planas.Id">Šalinti</a></td>
                                </tr>
                            }
                            @foreach (ReklamavimoLaikai laikas in ViewBag.ReklamavimoLaikai)
                            {
                                @if (laikas.FkReklamosPlanas == planas.Id)
                                {
                                    <tr>
                                        <td>Nuo: @laikas.ValandaNuo</td>
                                        <td>Iki: @laikas.ValandaIki</td>
                                        <td>H</td>
                                    </tr>
                                }
                            }
                        }
                    }
                }
            </thead>
        </table>
    </div>
}

IS_Turizmas/Views/Adverts/EditAdvert.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using IS_Turizmas.Models
@model IS_Turizmas.Models.Reklamos
@{
    ViewData["Title"] = "Redaguoti reklamą";
    <div class="container-fluid">
        <div class="col-md-10 mx-auto text-center py-3 my-3">
            <h1>Redaguojama reklama</h1>
        </div>
        <div class="row">
            <div class="col-md-10 mx-auto">
                <form asp-controller="Adverts" asp-action="AdvertEdit" enctype="multipart/form-data" method="POST">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label><strong>Pavadinimas</strong></label>
                        <input type="text" class="form-control" asp-for="Pavadinimas" placeholder="Įveskite reklamos pavadinimą" />
                        <span asp-validation-for="Pavadinimas" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label><strong>Dabartinis paveikslėlis</strong></label>
                        <img class="ad-image-preview img-thumbnail" src="~/@Model.Paveikslelis" />
                    </div>
                    <div class="form-group">
                        <label><strong>Naujas paveikslėlis (neprivaloma)</strong></label>
                        <input type="file" class="form-control" name="naujasPaveikslas"/>
                    </div>
                    <div class="form-group">
                        <label><strong>Tikslo url</strong></label>
                        <input type="text" class="form-control" asp-for="Url" placeholder="Įveskite url" />
                        <span asp-validation-for="Url" class="text-danger"></span>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Redaguoti</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

IS_Turizmas/Views/Adverts/ViewAdvertStatistics.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using IS_Turizmas.Models
@model IS_Turizmas.Models.Reklamos
@{
    ViewData["Title"] = "Reklamos statistika";
    <div class="col-md-10 mx-auto text-center py-3 my-3">
        <h1>Reklamos statistika</h1>
    </div>
    <div class="col-md-10 mx-auto">
        <table class="table table-striped text-center">
            <tr>
                <th>ID</th>
                <th>@Html.DisplayFor(model => Model.Id)</th>
            </tr>
            <tr>
                <th>Pavadinimas</th>
                <th>@Html.DisplayFor(model => Model.Pavadinimas)</th>
            </tr>
            <tr>
                <th>Paspaudimai</th>
                <th>@Html.DisplayFor(model => Model.Paspaudimai)</th>
            </tr>
            <tr>
                <th>Paveikslėlis</th>
                @*This is probably wrong*@
                <th><img class="ad-image-preview img-thumbnail" src="~/@Model.Paveikslelis" alt="Meme"></th>
            </tr>
        </table>
        <div class="col-md-4">
            <a asp-action="AdvertList">Grįžti</a>
        </div>
    </div>
}